import { existsSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import certificateData from "./award-certificates.json";
import { awardedPapers } from "@/lib/award";

/**
 * The award's data and the files rendered from it, checked against each
 * other.
 *
 * These files are generated by scripts/award-assets/render_award_assets.py
 * and committed, which means they can fall behind the data they were made
 * from without anything complaining: rename an author in people.json, forget
 * to re-run the script, and the page still builds while the certificate
 * names somebody who is no longer on the paper. Nothing in the type system
 * or the bundler looks at a PDF. These tests do.
 */

const repoRoot = fileURLToPath(new URL("../..", import.meta.url));
const publicDir = join(repoRoot, "public");

describe("the awarded paper", () => {
  it("is recorded on exactly one accepted paper", () => {
    // The card and the certificate can each show one paper. Two flagged
    // papers would silently render only the first.
    expect(awardedPapers).toHaveLength(1);
  });

  it("carries a link to the paper", () => {
    const [paper] = awardedPapers;

    expect(paper.url).not.toBe("");
    expect(() => new URL(paper.url)).not.toThrow();
  });
});

describe("the certificate manifest", () => {
  const { certificate } = certificateData;

  it("names the award recorded in people.json", () => {
    expect(certificateData.award).toBe(awardedPapers[0].award);
  });

  it("lists the paper's authors as the recipients", () => {
    // The certificate is issued to the paper's authors. If people.json is
    // edited and the script is not re-run, this is what catches it.
    expect(certificate.recipients).toBe(awardedPapers[0].authors);
  });

  it("points at a PDF that exists and is not empty", () => {
    const path = join(publicDir, certificate.file);

    expect(existsSync(path)).toBe(true);
    expect(statSync(path).size).toBeGreaterThan(1024);
  });

  it("points at a real PDF rather than an HTML error page", () => {
    const head = readFileSync(join(publicDir, certificate.file)).subarray(0, 5);

    expect(head.toString("latin1")).toBe("%PDF-");
  });

  it("uses a site-absolute path, so the link works from any route", () => {
    expect(certificate.file.startsWith("/")).toBe(true);
  });
});

describe("the social card", () => {
  const cardPath = join(publicDir, "best-paper-award-ogp.png");

  it("exists", () => {
    expect(existsSync(cardPath)).toBe(true);
  });

  it("is 1200x630, the size X and LinkedIn render without cropping", () => {
    // Read the dimensions out of the PNG's IHDR chunk: bytes 16-23 of the
    // file, big-endian width then height. Cheaper than a decoder, and the
    // only thing being asserted is the header.
    const png = readFileSync(cardPath);

    expect(png.subarray(1, 4).toString("latin1")).toBe("PNG");
    expect(png.readUInt32BE(16)).toBe(1200);
    expect(png.readUInt32BE(20)).toBe(630);
  });

  it("is under the 5MB limit crawlers enforce", () => {
    expect(statSync(cardPath).size).toBeLessThan(5 * 1024 * 1024);
  });
});
